/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as ConstructorsRouteImport } from './routes/constructors'
import { Route as IndexRouteImport } from './routes/index'

const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructorsRoute = ConstructorsRouteImport.update({
  id: '/constructors',
  path: '/constructors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/constructors': typeof ConstructorsRoute
  '/drivers': typeof DriversRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/constructors': typeof ConstructorsRoute
  '/drivers': typeof DriversRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/constructors': typeof ConstructorsRoute
  '/drivers': typeof DriversRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/constructors' | '/drivers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/constructors' | '/drivers'
  id: '__root__' | '/' | '/constructors' | '/drivers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConstructorsRoute: typeof ConstructorsRoute
  DriversRoute: typeof DriversRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constructors': {
      id: '/constructors'
      path: '/constructors'
      fullPath: '/constructors'
      preLoaderRoute: typeof ConstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConstructorsRoute: ConstructorsRoute,
  DriversRoute: DriversRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
